# [START runtime]
runtime: python27
threadsafe: true
# [END runtime]

handlers:
- url: /assets/(.*\.(ico$|jpg$|png$|gif$))$
  static_files: assets/\1
  upload: assets/.*\.(ico$|jpg$|png$|gif$)$
  application_readable: true

- url: /js/(.*\.(js$))$
  static_files: js/\1
  upload: js/.*\.(js$)$
  application_readable: true

- url: /css/(.*\.(css$))$
  static_files: css/\1
  upload: css/.*\.(css$)$
  application_readable: true

- url: /.*
  upload: index.html
  static_files: index.html
  secure: always
